services:
  # 使用 Docker 定義 cron 服務
  - type: cron
    name: trump-truthsocial-monitor
    env: docker
    dockerfilePath: ./Dockerfile
    # 設定每 2 分鐘執行一次
    schedule: "*/2 * * * *"
    # 持久儲存數據庫
    disk:
      name: data
      mountPath: /app
      sizeGB: 1
